part of 'theme.dart';

// Web
//  Dell genoa green / Flex tones Soft / Keep brand colors : Off / High background, low scaffold
// App
//  Brand blues / Flex tones Candy pop / Keep brand colors : Off / Very high scaffold, low surface

// Light and dark ColorSchemes made by FlexColorScheme v7.2.0.
// These ColorScheme objects require Flutter 3.7 or later.
const ColorScheme lightColorScheme = kIsWeb
    ? ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xff4a663a),
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffcbedb5),
        onPrimaryContainer: Color(0xff082101),
        secondary: Color(0xff57624e),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffdae7ce),
        onSecondaryContainer: Color(0xff141e0f),
        tertiary: Color(0xff426465),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffc4eaea),
        onTertiaryContainer: Color(0xff002021),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff410002),
        background: Color(0xfff5f7ee),
        onBackground: Color(0xff1a1c18),
        surface: Color(0xfff8f8f0),
        onSurface: Color(0xff1a1c18),
        surfaceVariant: Color(0xffdae0d2),
        onSurfaceVariant: Color(0xff43483e),
        outline: Color(0xff74796d),
        outlineVariant: Color(0xffc3c8bb),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff2f322d),
        onInverseSurface: Color(0xfff1f1ea),
        inversePrimary: Color(0xffafd09b),
        surfaceTint: Color(0xff4a663a),
      )
    : ColorScheme(
        brightness: Brightness.light,
        primary: Color(0xFF007AFF), //*
        onPrimary: Color(0xffffffff),
        primaryContainer: Color(0xffafc6ff),
        onPrimaryContainer: Color(0xff000d29),
        secondary: Color(0xff3c97d8),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffd7eaff),
        onSecondaryContainer: Color(0xff001d31),
        tertiary: Color(0xff2b74e2),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffedf0ff),
        onTertiaryContainer: Color(0xff001232),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff410002),
        background: Color(0xfffdfdfe),
        onBackground: Color(0xff131315),
        surface: Color(0xfffefefe),
        onSurface: Color(0xff131315),
        surfaceVariant: Color(0xffe8e6eb),
        onSurfaceVariant: Color(0xff1b1b1f),
        outline: Color(0xff46464a),
        outlineVariant: Color(0xffacabaf),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xff2f3032),
        onInverseSurface: Color(0xfffcf8fa),
        inversePrimary: Color(0xffd9e2ff),
        surfaceTint: Color(0xff1359c3),
      );

const ColorScheme darkColorScheme = kIsWeb
    ? ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffafd09b),
        onPrimary: Color(0xff1d3710),
        primaryContainer: Color(0xff334e25),
        onPrimaryContainer: Color(0xffcbedb5),
        secondary: Color(0xffbecab3),
        onSecondary: Color(0xff293323),
        secondaryContainer: Color(0xff3f4a38),
        onSecondaryContainer: Color(0xffdae7ce),
        tertiary: Color(0xffa9cdce),
        onTertiary: Color(0xff113637),
        tertiaryContainer: Color(0xff2a4c4d),
        onTertiaryContainer: Color(0xffc4eaea),
        error: Color(0xffffb4ab),
        onError: Color(0xff690005),
        errorContainer: Color(0xff93000a),
        onErrorContainer: Color(0xffffb4ab),
        background: Color(0xff21251e),
        onBackground: Color(0xffe3e3dc),
        surface: Color(0xff21251e),
        onSurface: Color(0xffe3e3dc),
        surfaceVariant: Color(0xff484e42),
        onSurfaceVariant: Color(0xffc3c8bb),
        outline: Color(0xff8d9286),
        outlineVariant: Color(0xff43483e),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe0e2d8),
        onInverseSurface: Color(0xff2f312d),
        inversePrimary: Color(0xff4a663a),
        surfaceTint: Color(0xffafd09b),
      )
    : ColorScheme(
        brightness: Brightness.dark,
        primary: Color(0xffafc6ff),
        onPrimary: Color(0xff001d4c),
        primaryContainer: Color(0xff1359c3),
        onPrimaryContainer: Color(0xfff6f6ff),
        secondary: Color(0xff5cb2f5),
        onSecondary: Color(0xff000f1d),
        secondaryContainer: Color(0xff0b7dbc),
        onSecondaryContainer: Color(0xffecf4ff),
        tertiary: Color(0xffcbdaff),
        onTertiary: Color(0xff00102d),
        tertiaryContainer: Color(0xff004494),
        onTertiaryContainer: Color(0xffe0e8ff),
        error: Color(0xffffb4ab),
        onError: Color(0xff310001),
        errorContainer: Color(0xff93000a),
        onErrorContainer: Color(0xffffedea),
        background: Color(0xff131315),
        onBackground: Color(0xfff3f0f1),
        surface: Color(0xff131315),
        onSurface: Color(0xfff3f0f1),
        surfaceVariant: Color(0xff303034),
        onSurfaceVariant: Color(0xffe3e2e6),
        outline: Color(0xff919094),
        outlineVariant: Color(0xff5e5e62),
        shadow: Color(0xff000000),
        scrim: Color(0xff000000),
        inverseSurface: Color(0xffe5e2e3),
        onInverseSurface: Color(0xff1b1b1d),
        inversePrimary: Color(0xff1359c3),
        surfaceTint: Color(0xffafc6ff),
      );
